---
# yum install -y \
#   yum-utils \
#   device-mapper-persistent-data \
#   lvm2
- name: Install required packages
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items:
  - device-mapper-persistent-data-0.7.3-3
  - lvm2-7:2.02.177-4
  - yum-utils-1.1.31-46

# # yum-config-manager \
# #   --add-repo \
# #   https://download.docker.com/linux/centos/docker-ce.repo
# This task is commented out in favour of the next one.
# - name: Set up the stable repository
#   copy:
#     src: docker-ce.repo
#     dest: /etc/yum.repos.d/docker-ce.repo

- name: Set up the stable repository
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

# yum install -y \
#   docker-ce
- name: Install Docker CE
  yum:
    pkg: docker-ce-18.06.1.ce-3
    state: installed
