---
# yum install -y \
#   yum-utils \
#   device-mapper-persistent-data \
#   lvm2
- name: Install required packages
  yum:
    pkg:
    - device-mapper-persistent-data
    - lvm2
    - yum-utils
    state: installed

# # yum-config-manager \
# #   --add-repo \
# #   https://download.docker.com/linux/centos/docker-ce.repo
# This task is commented out in favour of the next one.
# - name: Set up the stable repository
#   copy:
#     src: docker-ce.repo
#     dest: /etc/yum.repos.d/docker-ce.repo

- name: Set up the stable repository
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

# yum install -y \
#   docker-ce
- name: Install Docker CE
  yum:
    pkg: docker-ce-{{ docker_version }}.*
    state: installed

# systemctl daemon-reload
# systemctl start docker
# systemctl enable docker
- name: Start and enable the Docker service
  systemd:
    daemon-reload: yes
    name: docker
    state: started
    enabled: yes
